#!/usr/bin/env python3
"""Emit a C++ translation unit that makes MSVC verify the parsed IR.

Every struct in the IR is re-declared from its *source* field list (no
synthesised padding members) and paired with static_asserts for the size and
for every member offset the parser computed. If this file compiles, the
parser's model of MSVC x86 layout is correct by construction -- the compiler
itself is the oracle, so the wire offsets are not a claim we are making, they
are a claim cl.exe is checking.

Build it for x86 -- the emulator and the client are both 32-bit:

    cl /c /std:c++20 /EHsc verify_layout.cpp

Usage:
    python emit_verifier.py --ir protocol_099b.json --out verify_layout.cpp
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

PRELUDE = """// Generated by tools/protogen/emit_verifier.py -- do not edit.
//
// Compile-only artifact. Its sole purpose is to have MSVC confirm the struct
// layouts that tools/protogen/parse_protocol.py derived from the 0.99B (2.1.7)
// GameServer headers. A failure here means the parser's layout model drifted
// from the compiler's, and every generated packet binding is suspect.

#include <cstddef>
#include <cstdint>

using BYTE = unsigned char;
using WORD = unsigned short;
using DWORD = unsigned long;
using QWORD = unsigned long long;
using UINT = unsigned int;

"""


def emit(ir: dict) -> str:
    structs = ir["structs"]
    out = [PRELUDE]

    # Declaration order: dependencies before dependents.
    emitted: set[str] = set()
    remaining = dict(structs)
    while remaining:
        progressed = False
        for name, s in list(remaining.items()):
            deps = {m["type"] for m in s["members"]
                    if m.get("kind") == "struct"}
            if deps - emitted:
                continue

            members = [m for m in s["members"] if not m.get("padding")]
            # Packing can change mid-struct -- several headers open a pack(1)
            # region from inside the braces. Reproduce the transitions exactly,
            # otherwise MSVC would be judging a declaration we mistyped rather
            # than the layout the parser derived.
            pack = s["pack"]
            out.append(f"// {s['file']}\n")
            out.append(f"#pragma pack(push, {pack})\n")
            out.append(f"struct {name}\n{{\n")
            for m in members:
                if m.get("pack", pack) != pack:
                    pack = m["pack"]
                    out.append(f"#pragma pack({pack})\n")
                dims = "".join(f"[{d}]" for d in m.get("dims") or [])
                out.append(f"    {m['type']} {m['name']}{dims};\n")
            out.append("};\n")
            out.append("#pragma pack(pop)\n")
            out.append(
                f"static_assert(sizeof({name}) == {s['size']},\n"
                f"              \"{name}: size drift vs parsed IR\");\n")
            for m in members:
                out.append(
                    f"static_assert(offsetof({name}, {m['name']}) == {m['offset']},\n"
                    f"              \"{name}.{m['name']}: offset drift vs parsed IR\");\n")
            out.append("\n")

            emitted.add(name)
            del remaining[name]
            progressed = True
        if not progressed:
            raise SystemExit(f"error: cyclic struct dependency among {sorted(remaining)}")

    out.append(f"// {len(emitted)} structs verified.\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ir", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    ir = json.loads(args.ir.read_text(encoding="utf-8"))
    args.out.write_text(emit(ir), encoding="utf-8")
    n = len(ir["structs"])
    print(f"emitted {args.out} ({n} structs, "
          f"{sum(len([m for m in s['members'] if not m.get('padding')]) for s in ir['structs'].values())} offset asserts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
