namespace MuServer.GameServer.World;

/// <summary> PARTIAL port of CItem::Convert (Item.cpp:122-620) and of the getters CItem::GetDamageMin/Max/
/// GetDefense/GetDefenseSuccessRate (Item.cpp:1007-1053) -- only the LINEAR per-upgrade-level (+0..+15) scaling
/// that always applies to any item, without the excellent-item branches (<c>NewOption</c>) nor set-item
/// (<c>SetOption</c>+ItemInfo.Level bonus) ones, which depend on ItemOption.txt/SetItemOption.txt (not ported
/// yet -- see World/ItemBalance.cs). Since no item generated by this port carries those options activated today
/// (always NewOption=SetOption=0), those branches of the original would never execute anyway. Formula
/// (Item.cpp:351-403 for damage, 432-450 for DefenseSuccessRate/MagicDamageRate, 457-504 for Defense): <c>value
/// = base + (level*3)</c>, plus a quadratic "extra" (triangular numbers) for levels +10 to +15:
/// <c>+((level-9)*(level-8))/2</c> -- gives +1,+3,+6,+10,+15,+21 at +10..+15. Shields (section 6) scale Defense
/// differently: flat <c>+level</c>, without the quadratic "extra" (Item.cpp:457-462). All the getters return 0
/// if the item is broken (<see cref="Item.Durability"/>==0), like the original. </summary>
public static class ItemCombatMath
{
    private static int LevelScaled(int baseValue, int level)
    {
        int value = baseValue + (level * 3);

        if (level >= 10)
        {
            value += ((level - 9) * (level - 8)) / 2;
        }

        return value;
    }

    private static int ShieldLevelScaled(int baseValue, int level) => baseValue + level;

    public static int GetDamageMin(Item item, ItemBalance info) =>
        item.Durability == 0 ? 0 : LevelScaled(info.DamageMin, item.Level);

    public static int GetDamageMax(Item item, ItemBalance info) =>
        item.Durability == 0 ? 0 : LevelScaled(info.DamageMax, item.Level);

    public static int GetDefense(Item item, ItemBalance info) =>
        item.Durability == 0 ? 0 : info.IsShield ? ShieldLevelScaled(info.Defense, item.Level) : LevelScaled(info.Defense, item.Level);

    public static int GetDefenseSuccessRate(Item item, ItemBalance info) =>
        item.Durability == 0 ? 0 : LevelScaled(info.DefenseSuccessRate, item.Level);

    public static int GetMagicDefense(Item item, ItemBalance info) =>
        item.Durability == 0 ? 0 : LevelScaled(info.MagicDefense, item.Level);

    // AttackSpeed/WalkSpeed are NOT scaled by level in the original (they are fixed values of the Item.txt row)
    // -- they are exposed here anyway with the same durability=0 check for consistent use.
    public static int GetAttackSpeed(Item item, ItemBalance info) => item.Durability == 0 ? 0 : info.AttackSpeed;
    public static int GetWalkSpeed(Item item, ItemBalance info) => item.Durability == 0 ? 0 : info.WalkSpeed;

    /// <summary>Puerto de CItemManager::GetItemDurability (ItemManager.cpp:393-450).</summary>
    public static int GetItemDurability(Item item, ItemBalance info)
    {
        if (!item.IsItem()) return 0;
        int baseDur = info.Durability > 0 ? info.Durability : info.MagicDurability;
        if (baseDur == 0) return 0;

        int level = item.Level;
        int dur;
        if (level >= 5)
        {
            dur = level switch
            {
                10 => baseDur + ((level * 2) - 3),
                11 => baseDur + ((level * 2) - 1),
                12 => baseDur + ((level * 2) + 2),
                13 => baseDur + ((level * 2) + 6),
                14 => baseDur + ((level * 2) + 11),
                15 => baseDur + ((level * 2) + 17),
                _ => baseDur + ((level * 2) - 4),
            };
        }
        else
        {
            dur = baseDur + level;
        }

        return Math.Clamp(dur, 0, 255);
    }

    /// <summary>Puerto de CItemManager::GetItemRepairMoney (ItemManager.cpp:465-530).</summary>
    public static int GetItemRepairMoney(Item item, byte type, ItemBalance info)
    {
        if (!item.IsItem()) return 0;
        int maxDur = GetItemDurability(item, info);
        if (maxDur <= 0 || item.Durability >= maxDur) return 0;

        int buyMoney = info.BuyMoney > 0 ? info.BuyMoney : (info.Level * info.Level * 100);
        int repairMoney = (item.Index == 3332 || item.Index == 3333) ? buyMoney : buyMoney / 3;

        repairMoney = Math.Min(repairMoney, 2_000_000_000);
        if (repairMoney >= 100) repairMoney = (repairMoney / 10) * 10;
        if (repairMoney >= 1000) repairMoney = (repairMoney / 100) * 100;

        double sq1 = Math.Sqrt(repairMoney);
        double sq2 = Math.Sqrt(sq1);
        double durFactor = 1.0 - ((double)item.Durability / maxDur);
        double value = ((3.0 * sq1 * sq2) * durFactor) + 1.0;

        if (item.Durability == 0)
        {
            value *= (item.Index == 3332 || item.Index == 3333) ? 2.0 : 1.4;
        }

        int money = (int)(type == 1 ? value * 2.5 : value);
        if (money >= 100) money = (money / 10) * 10;
        if (money >= 1000) money = (money / 100) * 100;

        return Math.Max(money, 1);
    }

    /// <summary>Port of CItem::Convert (Item.cpp:247-280) -- computation of stat requirements scaled by the item's level.</summary>
    public static int GetRequireStrength(Item item, ItemBalance info)
    {
        if (info.RequireStrength == 0) return 0;
        int itemLevel = info.Level;
        return (((info.RequireStrength * ((item.Level * 3) + itemLevel)) * 3) / 100) + 20;
    }

    public static int GetRequireDexterity(Item item, ItemBalance info)
    {
        if (info.RequireDexterity == 0) return 0;
        int itemLevel = info.Level;
        return (((info.RequireDexterity * ((item.Level * 3) + itemLevel)) * 3) / 100) + 20;
    }

    public static int GetRequireVitality(Item item, ItemBalance info)
    {
        if (info.RequireVitality == 0) return 0;
        int itemLevel = info.Level;
        return (((info.RequireVitality * ((item.Level * 3) + itemLevel)) * 3) / 100) + 20;
    }

    public static int GetRequireEnergy(Item item, ItemBalance info)
    {
        if (info.RequireEnergy == 0) return 0;
        int itemLevel = info.Level;
        if (info.Section == 5 && info.Slot == 1) // Staffs
        {
            return (((info.RequireEnergy * (item.Level + itemLevel)) * 3) / 100) + 20;
        }

        return (((info.RequireEnergy * ((item.Level * 3) + itemLevel)) * 4) / 100) + 20;
    }

    public static int GetRequireLeadership(Item item, ItemBalance info)
    {
        if (info.RequireLeadership == 0) return 0;
        int itemLevel = info.Level;
        return (((info.RequireLeadership * ((item.Level * 3) + itemLevel)) * 3) / 100) + 20;
    }

    public static int GetRequireLevel(Item item, ItemBalance info)
    {
        if (info.RequireLevel == 0) return 0;
        if (item.Index < 384) // Secciones 0 a 11 (Armas y Armaduras)
        {
            return info.RequireLevel;
        }

        if (item.Index is >= 387 and <= 390) // GET_ITEM(12,3) .. GET_ITEM(12,6) Alas
        {
            return info.RequireLevel + (item.Level * 5);
        }

        if (item.Index is >= 391 and <= 408 && item.Index != 399) // Orbes
        {
            return info.RequireLevel;
        }

        return info.RequireLevel + (item.Level * 4);
    }

    /// <summary>Puerto de CItemManager::CheckItemRequireClass (ItemManager.cpp:682-709).</summary>
    public static bool CanEquipClass(byte playerClass, byte changeUp, ItemBalance info)
    {
        if (playerClass >= info.RequireClass.Length) return false;
        int reqClass = info.RequireClass[playerClass];
        if (reqClass == 0) return false;
        return (changeUp + 1) >= reqClass;
    }

    /// <summary>Puerto de CItemManager::CheckItemMoveToInventory (ItemManager.cpp:758-779) -- compatibilidad de slot.</summary>
    public static bool CanEquipSlot(Item item, int targetSlot, ItemBalance info, ItemBalanceTable itemBalance, PlayerObject player)
    {
        if (info.Slot < 0 || targetSlot < 0 || targetSlot >= Item.InventoryWearSize)
        {
            return false;
        }

        // Weapon/shield/bow/staff slots (0 and 1)
        if (targetSlot is 0 or 1)
        {
            if (info.Slot is not (0 or 1))
            {
                return false;
            }

            if (targetSlot == 0)
            {
                var weapon2 = player.Items[1];
                if (weapon2.IsItem())
                {
                    // Flechas/Pernos (GET_ITEM(4,7)=135, GET_ITEM(4,15)=143) permitidos con arma de 2 manos
                    if (info.TwoHand && weapon2.Index != 135 && weapon2.Index != 143)
                    {
                        return false;
                    }
                }
            }
            else if (targetSlot == 1)
            {
                var weapon1 = player.Items[0];
                if (weapon1.IsItem())
                {
                    var weapon1Info = itemBalance.Get(weapon1.Index);
                    if (weapon1Info != null && weapon1Info.TwoHand && item.Index != 135 && item.Index != 143)
                    {
                        return false;
                    }
                }
            }

            return true;
        }

        // Slots de anillos (10 y 11)
        if (targetSlot is 10 or 11)
        {
            return info.Slot is 10 or 11;
        }

        // Resto de slots (2=Casco, 3=Armadura, 4=Pantalones, 5=Guantes, 6=Botas, 7=Alas, 8=Mascota, 9=Colgante)
        return info.Slot == targetSlot;
    }

    /// <summary>Port of CItemManager::CheckItemMoveToInventory (ItemManager.cpp:711-780) -- full validation for equipping an item.</summary>
    public static bool CheckItemMoveToInventory(PlayerObject player, Item item, int targetSlot, ItemBalance info, ItemBalanceTable itemBalance)
    {
        if (!item.IsItem()) return false;

        // If the destination slot is in the main inventory (12-107), moving is always allowed
        if (targetSlot >= Item.InventoryWearSize)
        {
            return true;
        }

        if (player.Level < GetRequireLevel(item, info)) return false;
        if (player.Strength < GetRequireStrength(item, info)) return false;
        if (player.Dexterity < GetRequireDexterity(item, info)) return false;
        if (player.Vitality < GetRequireVitality(item, info)) return false;
        if (player.Energy < GetRequireEnergy(item, info)) return false;
        if (player.Leadership < GetRequireLeadership(item, info)) return false;
        if (!CanEquipClass(player.Class, player.ChangeUp, info)) return false;
        if (!CanEquipSlot(item, targetSlot, info, itemBalance, player)) return false;

        return true;
    }
}
